name: CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a simple script
      run: echo Hello, world!
    - name: Run multiline script
      run: |
        echo Add other actions to build
        ls
        echo end
    - name: Run some Python
      run: python main.py
      
